name: CICD
on:
    push:
        branches: [main]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@main
            - name: Use Node.js
              uses: actions/setup-node@main
              with:
                  node-version: '12.x'
            - name: Install dependencies
              run: yarn install
            - run: yarn test
            - run: yarn build
            - name: GitHub Action for Firebase
              uses: w9jds/firebase-action@v2.0.0
              with:
                  args: deploy only hosting
              env:
                  FIREBASE_TOKEN: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_TIME_ZONE_CONVERTER_3A99A }}
