name: Deploy to Firebase Hosting
'on':
  push:
    branches: [main]
jobs:
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@main
    - uses: actions/setup-node@main
      with:
      node-version: '12.x'
    - run: yarn install && yarn build
    - name: GitHub Action for Firebase
      uses: w9jds/firebase-action@main
      with:
        args: deploy only hosting
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_TIME_ZONE_CONVERTER_3A99A }}
