name: Continuous Integration

on:
    pull_request:
        branch: [main]

jobs:
    test_pull_request:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@2
              with:
                  node-version: 12
            - run: npm ci
            - run: yarn test
            - run: yarn build
